"""empty message

Revision ID: fb4a2afdc322
Revises: 25d348ee151c
Create Date: 2026-04-18 12:20:24.350390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4a2afdc322'
down_revision = '25d348ee151c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mineral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('download_time', sa.DateTime(), nullable=True),
    sa.Column('id_rack', sa.Integer(), nullable=False),
    sa.Column('num_shelf', sa.Integer(), nullable=False),
    sa.Column('num_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_rack'], ['rack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('object')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('download_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('mineral')
    op.drop_table('rack')
    # ### end Alembic commands ###
